name: Publish MOCT on release

on:
  release:
    types: [ published ]

jobs:
  test-linux:
    name: Test MOCT on Ubuntu before publishing
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pip
        run: pip install --upgrade pip
      - name: Test package
        run: python test.py
  test-macos:
    name: Test MOCT on macOS before publishing
    runs-on: macos-latest
    steps:
      - name: Setup Pip
        run: pip install --upgrade pip
      - name: Test package
        run: python test.py
  test-windows:
    name: Test MOCT on Windows before publishing
    runs-on: windows-latest
    steps:
      - name: Setup Pip
        run: python -m pip install --upgrade pip
      - name: Test package
        run: python test.py
  publish:
    name: Publish MOCT after all checks have been completed
    runs-on: ubuntu-latest
    needs: [ test-linux, test-macos, test-windows ]
    steps:
      - name: Update Pip
        run: pip install --upgrade pip
      - name: Publish MOCT to Pip
        run: "echo This won't happen yet."
