name: Publish MOCT on release

on:
  release:
    types: [ published ]

jobs:
  test:
    name: Test MOCT before publishing
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test@d157ff6
  publish:
    name: Publish MOCT after all checks have been completed
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Update Pip
        run: pip install --upgrade pip
      - name: Publish MOCT to Pip
        run: echo Do something
