name: Test MOCT on push

on:
  push:
    branches: master
  pull_request:
    branches: master
    types: [ opened, reopened, synchronize ]

jobs:
  ubuntu-test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Pip
        run: pip install --upgrade pip
      - name: Install depencies
        run: pip install -r requirements.txt
      - name: Check for syntax errors
        run: python __init__.py
      - name: Test package
        run: python test.py
  macos-test:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Pip
        run: pip install --upgrade pip
      - name: Install dependancies
        run: pip install -r requirements.txt
      - name: Check for syntax errors
        run: python __init__.py
      - name: Test package
        run: python test.py
  windows-test:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Pip
        run: python -m pip install --upgrade pip
      - name: Install dependancies
        run: python -m pip install -r requirements.txt
      - name: Check for syntax errors
        run: python __init__.py
      - name: Test package
        run: python test.py
