name: Test MOCT on push

on:
  push:
    branches: master
  pull_request:
    branches: master
    types: [ opened, reopened, synchronize ]

jobs:
  ubuntu-test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Setup PiP
        run: pip install --upgrade pip
      - name: Test package
        run: cd ../; ls
  macos-test:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - name: Setup PiP
        run: pip install --upgrade pip
      - name: Test package
        run: python test.py
  windows-test:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - name: Setup Pip
        run: python -m pip install --upgrade pip
      - name: Test package
        run: python test.py
